Add authentication
12urenloop/Telraam pull request #52
Opened 2021-10-13 01:30 UTC by mcbloch

also fix a classname lookup on a 404.

## Usage in code

No annotation means you don't need to be authenticated
`@PermitAll` means all authenticated users can access the resource
`@DenyAll` means nobody can access it
`@Auth Optional<User> userOpt` as path parameter means authentication is not required and gives you a user object, even for anonymous users. Useful to to remove authentication for 1 method when auth is required for the rest of the class

For more see the docs https://www.dropwizard.io/en/latest/manual/auth.html

## Using the api

Authenticate using basic auth specifying a username:password. The password is a common one at the moment. When it's valid, your specified username can be used for further authorization.
Password at the moment is **'secret'**.
All Create, Update and Delete methods now require authentication.

### Examples

Valid authentication:
`http -a username:secret localhost:8080/hello-world/auth`

Invalid authentication:
`http -a username:invalid localhost:8080/hello-world/auth`

Using curl:
`curl -u username:secret localhost:8080/hello-world/auth`

2021-11-12 13:01 UTC, Robbe7730 requested changes
Minor nitpick, looks good otherwise :slightly_smiling_face:

2021-11-12 13:01 UTC, Robbe7730 commented on src/main/java/telraam/App.java
>                              // If the password is 'secret' then create a user with the specified username
```suggestion

```

2022-03-03 20:15 UTC, abeforgit commented
note this is breaking for all currently existing clients

2022-03-03 20:16 UTC, abeforgit commented
recommend to merge _after_ test-day

2023-03-06 21:28 UTC, redfast00 commented
We've decided to not do authentication

2023-03-06 21:28 UTC, closed without merging